global:
  registry: 280768229384.dkr.ecr.ap-south-1.amazonaws.com
  awsRegion: ap-south-1
  mongoDb: streamingapp
  clientUrls: "http://localhost:3000"

services:
  auth:
    image: streamingapp-auth
    tag: "1.0.0"
    replicas: 2
    port: 3001
    probe: { type: http, path: /health }
  streaming:
    image: streamingapp-streaming
    tag: "1.0.0"
    replicas: 2
    port: 3002
    probe: { type: http, path: /api/health }
  admin:
    image: streamingapp-admin
    tag: "1.0.0"
    replicas: 2
    port: 3003
    probe: { type: tcp }
  chat:
    image: streamingapp-chat
    tag: "1.0.0"
    replicas: 2
    port: 3004
    probe: { type: tcp }

frontend:
  image: streamingapp-frontend
  tag: "1.0.0"
  replicas: 2
  port: 80

mongo:
  image: mongo:6
  storageSize: 5Gi

secrets:
  jwtSecret: "change-me"
  awsS3Bucket: ""
  awsCdnUrl: ""

ingress:
  enabled: true
  className: nginx
  host: ""
